name       : keybase
version    : 2.10.1
release    : 4
source     :
 - git|https://github.com/keybase/client : v2.10.1
 - git|https://github.com/keybase/kbfs   : v2.10.1
license    : BSD-3-Clause
component  : security.crypto
networking : yes
summary    : Keybase command-line client, filesystem and GUI
description: |
    The Keybase app helps you perform cryptographically-secure operations with
    people you know on the Internet: chatting, file sharing, even publishing
    public documents. It's all easier and safer with Keybase.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-x11-2.0)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - git
    - golang
    - rsync
    - yarn
rundeps    :
    - fuse
    - gconf
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-opt-by-usr-share.patch

    # The installer expects the kbfs data in `..`
    ln -s "$sources/kbfs.git" "../kbfs"
build      : |
    export KEYBASE_SKIP_32_BIT=1
    ./packaging/linux/build_binaries.sh prerelease ./build_dir
install    : |
    # Create required directories
    install -dm00755 $installdir/keybase

    # Copy files
    cp -Rv ./build_dir/binaries/amd64/usr $installdir/

    # Keybase redirector maps /keybase to the /run/user/$UID/keybase/kbfs.
    # It requires set-uid to function.
    chmod 4755 $installdir/usr/bin/keybase-redirector

    # Cleanup extra files
    rm $installdir/usr/share/keybase/post_install.sh
