name       : keybase
version    : 5.9.1
release    : 32
source     :
    - git|https://github.com/keybase/client : v5.9.1
license    : BSD-3-Clause
component  : security.crypto
networking : yes
summary    : Keybase command-line client, filesystem and GUI
description: |
    The Keybase app helps you perform cryptographically-secure operations with people you know on the Internet: chatting, file sharing, even publishing public documents. It's all easier and safer with Keybase.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(xscrnsaver)
    - golang
    - rsync
    - yarn
rundeps    :
    - fuse
    - gconf
    - nodejs
environment: |
    go env -w GO111MODULE=auto
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-opt-by-usr-share.patch
    %patch -p1 < $pkgfiles/0001-Update-version-to-5.9.1.patch
build      : |
    export KEYBASE_SKIP_32_BIT=1
    ./packaging/linux/build_binaries.sh prerelease ./build_dir
install    : |
    # Create required directories
    install -dm00755 $installdir/keybase

    # Copy files
    cp -Rv ./build_dir/binaries/amd64/usr $installdir/

    # Keybase redirector maps /keybase to the /run/user/$UID/keybase/kbfs.
    # It requires set-uid to function.
    chmod 4755 $installdir/usr/bin/keybase-redirector

    # Cleanup extra files
    rm $installdir/usr/share/keybase/post_install.sh
